name: Docker Latest - Standard

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"
  pull_request:
    tags-ignore:
      - "*"
    branches-ignore:
      - "*"

jobs:
  # Distroless build.
  distroless:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - '16'

    name: Tag Latest Distroless (node:${{ matrix.node }})

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: quay.io/soketi/soketi
          tags: |
            type=raw,value=latest-${{ matrix.node }}-distroless

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.distroless
          build-args: |
            VERSION=${{ matrix.node }}
          cache-from: |
            type=gha,scope=distroless
          cache-to: |
            type=gha,scope=distroless
          platforms: |
            linux/amd64
            linux/arm64

  # Debian build.
  debian:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - '16'

    name: Tag Latest Debian (node:${{ matrix.node }})

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: quay.io/soketi/soketi
          tags: |
            type=raw,value=latest-${{ matrix.node }}-debian

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.debian
          build-args: |
            VERSION=${{ matrix.node }}
          cache-from: |
            type=gha,scope=debian
          cache-to: |
            type=gha,scope=debian
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
